/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.data
 */
package org.vidad.data;

import java.util.Date;

import org.apache.log4j.Logger;
import org.bson.types.ObjectId;
import org.vidad.tools.conf.Collection;

/**
 * @author Moshe Beeri
 *
 */
public class Tag extends Collectionable<Tag>{
	transient Logger log = Logger.getLogger(Tag.class);
	Date 		creationDate;
	String		taxonomy;
	ObjectId	parentId;
	
	/**
	 * @return
	 * @see org.vidad.data.Collectionable#getCollection()
	 */
	@Override
	public Collection getCollection() {
		return Collection.TAG;
	}
}
