/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.camel
 */
package org.vidad.data;

import java.util.ArrayList;

import org.apache.log4j.Logger;


/**
 * @author Moshe Beeri
 *
 */
public class Tasks extends ArrayList<Task> {
	private static final long serialVersionUID = 9077371874941500374L;
	transient Logger log = Logger.getLogger(Tasks.class);
	/**
	 * @param task
	 * @return
	 */
	public static Tasks fromTask(Task task) {
		Tasks ret = new Tasks();
		ret.add(task);
		return ret;
	}
}
