/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.data
 */
package org.vidad.data;

import java.util.Date;

import org.apache.log4j.Logger;
import org.joda.time.DateTime;
import org.vidad.tools.conf.Collection;

/**
 * @author Moshe Beeri
 *
 */
public class Video extends Collectionable<Video>{
	transient Logger log = Logger.getLogger(Video.class);
	
	String	extension;
	String	videoURL;
	Date	receivedTime;
	
	
	
	/**
	 * @param videoURL
	 * @param extension
	 */
	public Video(String videoURL, String extension) {
		super();
		this.extension = extension;
		this.videoURL = videoURL;
		receivedTime = new DateTime().toDate();
	}



	/**
	 * @return
	 * @see org.vidad.data.Collectionable#getCollection()
	 */
	@Override
	public Collection getCollection() {
		return Collection.VIDEO;
	}
}
