/**
 * This file was generated by Moshe Beeri
 * Apr 23, 2013
 * com.orbograph.cloudtools.conf
 */
package org.vidad.tools.conf;

import java.io.Serializable;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

/**
 * @author Moshe Beeri
 *
 */
@Root
public class MongoConfig implements Serializable{


	/**
	 * serialVersionUID -
	 */
	private static final long serialVersionUID = -9128002251045074254L;

	//network
    @Element
    String host;
    @Element
    int port;
    @Element
    boolean authenticate;
    @Element
    boolean tenanted;
    //DB admin user credentials
    @Element
    String adminUser;
    @Element
    String adminPassword;
    //DB user credentials
    @Element
    String dbName;
    @Element
    String user;
    @Element
    String password;
    
	protected MongoConfig() {
		super();
	}

	public static MongoConfig create() {
		return new MongoConfig("localhost",27017, true, true,
				"admin","admin password",
				"db user","db user password",
				"vidad");
	}

	public MongoConfig(	String host, int port, boolean authenticate,
					boolean tenanted,
					String adminUser, String adminPassword, 
					String user, String password,
					String dbName) {
		super();
		this.host = host;
		this.port = port;
		this.authenticate = authenticate;
		this.tenanted = tenanted;
	    this.adminUser     = adminUser    ;
	    this.adminPassword = adminPassword;
		this.user = user;
		this.password = password;
		this.dbName = dbName;
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public int getPort() {
		return port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the adminUser
	 */
	public String getAdminUser() {
		return adminUser;
	}

	/**
	 * @param adminUser the adminUser to set
	 */
	public void setAdminUser(String adminUser) {
		this.adminUser = adminUser;
	}

	/**
	 * @return the adminPassword
	 */
	public String getAdminPassword() {
		return adminPassword;
	}

	/**
	 * @param adminPassword the adminPassword to set
	 */
	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	/**
	 * @return the dbName
	 */
	public String getDbName() {
		return dbName;
	}

	/**
	 * @param dbName the dbName to set
	 */
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	/**
	 * @return the authenticate
	 */
	public boolean isAuthenticate() {
		return authenticate;
	}

	/**
	 * @param authenticate the authenticate to set
	 */
	public void setAuthenticate(boolean authenticate) {
		this.authenticate = authenticate;
	}

	/**
	 * @return the tenanted
	 */
	public boolean isTenanted() {
		return tenanted;
	}

	/**
	 * @param tenanted the tenanted to set
	 */
	public void setTenanted(boolean tenanted) {
		this.tenanted = tenanted;
	}
}
