/**
 * This file was generated by Moshe Beeri
 * Aug 8, 2013
 * org.vidad.service
 */
package org.vidad.tools.service;

import javax.ws.rs.Consumes;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

import org.apache.log4j.Logger;
import org.vidad.data.Tag;
import org.vidad.tools.rest.MongoRestService;


/**
 * @author Moshe Beeri
 *
 */
@Path("/tag")
@Consumes("application/json")
@Produces("application/json")
public class TagRest extends MongoRestService<Tag> {
	Logger log = Logger.getLogger(TagRest.class);
}
