/**
 * This file was generated by Moshe Beeri
 * May 19, 2013
 * com.orbograph.conf
 */
package org.vidad.tools.conf;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Moshe Beeri
 *
 */
public enum Collection{
	EXCEPTION("exception"), 
	UNITTEST("unittest"),
	TRANSMISSION("transmission"),
	CONTEXT("context"), 
	ORIGINAL("original"), 
	PAGE("page"), 
	EOB("eob"), 
	OCR("ocr"), 
	LAYOUT("layout"), 
	CORPUS("corpus"),
	CLUSTER("cluster"), 
	CLUSTERSET("clusterset"), 
	REPORT("report"), 
	CLAIM("claim"), 
	KZERO("kzero"),
	KZERO_REQUEST("k0request"),
	KONE_REQUEST("k1request"),
	KTWO_REQUEST("k2request"), 
	KZERO_RESPONSE("k0response"), 
	KONE_RESPONSE("k1response"), 
	KTWO_RESPONSE("k2response"), 
	KZERO_TASK("k0task"), 
	KONE_TASK("k1task"), 
	KTWO_TASK("k2task"), 
	REFERRENCE("reference"), 
	KZERO_IMAGE("kzeroimage"), 
	;
	
	String name;
	static List<Collection> all = new ArrayList<Collection>();
	static Map<String,Collection> map = new HashMap<String,Collection>();
	/**
	 * @param name
	 */
	private Collection(String name) {
		this.name = name;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	
	public static List<Collection> all(){
		if(!all.isEmpty())
			return all;
		all = new ArrayList<Collection>();
		for (Collection c : Collection.values())
			all.add(c);
		return all;
	}
	
	public static Collection fromString(String name){
		if(map.isEmpty())
			for (Collection c : Collection.values())
				map.put(c.getName(), c);
		Collection c = map.get(name.toLowerCase());
		if(c==null)
			throw new IllegalArgumentException("enum: "+name+" is not part of enum Collection");
		return c;
	}	
}

