/**
 * This file was generated by Moshe Beeri
 * Aug 26, 2013
 * org.vidad.tag.model
 */
package org.vidad.tag.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import org.openfaces.util.Faces;

/**
 * @author Moshe Beeri
 *
 */
@ManagedBean	
@RequestScoped
public class TagCollector  implements Serializable{

	private static final long serialVersionUID = 4930140495481611695L;
	String tagName;
	public Converter getTagNameConverter(){
		return new Converter() {
			
			@Override
			public String getAsString(FacesContext context, UIComponent converter, Object value) {
				System.out.println("getAsString=" +(String)value);
				return (String)value;
			}
			
			@Override
			public Object getAsObject(FacesContext context, UIComponent converter, String value) {
				System.out.println("getAsObject=" +value);
				return value;
			}
		};
	}

	public List<String> getSuggestedTags(){
		String searchString = Faces.var("searchString", String.class);
		System.out.println("getSuggestedTags searchString="+ searchString);
		List<String> suggestedTags = Arrays.asList(new String[]{"ford", "mazda", "fiat"});
		return suggestedTags;	
	}

	public String getTagName() {
		return tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}
}
