/**
 * This file was generated by Moshe Beeri
 * Aug 26, 2013
 * org.vidad.tag.model
 */
package org.vidad.tag.model;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.event.AjaxBehaviorEvent;

import org.vidad.data.NamedId;

/**
 * @author Moshe Beeri
 *
 */
@ManagedBean	
@RequestScoped
public class TagCollector  implements Serializable{

	private static final long serialVersionUID = 4930140495481611695L;
	NamedId value;
	String valueName;
	String valueId;
	String status;
	
	public void add(AjaxBehaviorEvent e){
		status = "valueName="+valueName + " valueId="+valueId;	
	}

	public NamedId getValue() {
		return value;
	}

	public void setValue(NamedId value) {
		this.value = value;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getValueName() {
		return valueName;
	}

	public void setValueName(String valueName) {
		this.valueName = valueName;
	}

	public String getValueId() {
		return valueId;
	}

	public void setValueId(String valueId) {
		this.valueId = valueId;
	}
	
}
