/**
 * This file was generated by Moshe Beeri
 * Aug 13, 2013
 * org.vidad.tag.model
 */
package org.vidad.tag.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.vidad.data.Tag;
import org.vidad.tools.nosql.Mongodb;

/**
 * @author Moshe Beeri
 *
 */
@ManagedBean	
@RequestScoped
public class VideoTagCollector  implements Serializable{
	/**
	 * serialVersionUID -
	 */
	private static final long serialVersionUID = -5849533532636382036L;
	transient Logger log = Logger.getLogger(VideoTagCollector.class);
	
	boolean initial = true;
	String status="";
	String tagName="";
	@ManagedProperty(value = "#{param.videoId}")
	String videoId;
	String taxonomyId= "";	
	double videoTimeStamp=0d;
	
	List<String> tags = new ArrayList<String>();
	
	public VideoTagCollector() {
		super();
	}

	protected void insertTag(){
		Tag tag = new Tag(tagName, taxonomyId, videoTimeStamp, "");
		Mongodb.getInstance().insertCollectionable(tag);		
	}
	
	@SuppressWarnings("unchecked")
	public void add(AjaxBehaviorEvent e){
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);       
        if(session.getAttribute("tags")!=null)
        	tags = (List<String>) session.getAttribute("tags");
        else
        	session.setAttribute("tags", tags);
		//log.info(e.getSource().toString());
		String messge = "tag created for videoId: " + videoId + " taxonomy: "+tagName +" at video time: " + videoTimeStamp;
		log.info(messge);
		initial=false;
		status = messge;
		tags.add(tagName);
		for(String t : tags)
			System.out.println(t);
	}
	
	public void reset(AjaxBehaviorEvent e){
		status="";
		tagName="";
		videoTimeStamp=0d;
		tags = new ArrayList<String>();
	}

	/**
	 * @return the initial
	 */
	public boolean isInitial() {
		return initial;
	}

	/**
	 * @param initial the initial to set
	 */
	public void setInitial(boolean initial) {
		this.initial = initial;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public String getTagName() {
		return tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public double getVideoTimeStamp() {
		return videoTimeStamp;
	}

	public void setVideoTimeStamp(double videoTimeStamp) {
		this.videoTimeStamp = videoTimeStamp;
	}

	public List<String> getTags() {
		return tags;
	}

	public void setTags(List<String> tags) {
		this.tags = tags;
	}

	public String getVideoId() {
		return videoId;
	}

	public void setVideoId(String videoId) {
		this.videoId = videoId;
	}

	public String getTaxonomyId() {
		return taxonomyId;
	}

	public void setTaxonomyId(String taxonomyId) {
		this.taxonomyId = taxonomyId;
	}

}
