/**
 * This file was generated by Moshe Beeri
 * Aug 13, 2013
 * org.vidad.tag.model
 */
package org.vidad.tag.model;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.AjaxBehaviorEvent;

import org.apache.log4j.Logger;
import org.vidad.data.Tag;

/**
 * @author Moshe Beeri
 *
 */
@ManagedBean	
@SessionScoped
public class VidoeTagCollector  extends Tag implements Serializable{
	/**
	 * serialVersionUID -
	 */
	private static final long serialVersionUID = -5849533532636382036L;
	Logger log = Logger.getLogger(VidoeTagCollector.class);
	boolean initial = true;
	String status="";
	String taxonomy="";
	
	public void addX(AjaxBehaviorEvent e){
		add();	
	}
	
	public String add(){
		log.info("taxonomy: "+taxonomy +" added");
		initial=false;
		status = taxonomy + " added"; 
		return "added";
	}
	
	public String reset(){
		return "added";
	}

	/**
	 * @return the initial
	 */
	public boolean isInitial() {
		return initial;
	}

	/**
	 * @param initial the initial to set
	 */
	public void setInitial(boolean initial) {
		this.initial = initial;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the taxonomy
	 */
	public String getTaxonomy() {
		return taxonomy;
	}

	/**
	 * @param taxonomy the taxonomy to set
	 */
	public void setTaxonomy(String taxonomy) {
		this.taxonomy = taxonomy;
	}

}
