/**
 * This file was generated by Moshe Beeri
 * Aug 13, 2013
 * org.vidad.tag.model
 */
package org.vidad.tag.model;

import org.apache.log4j.Logger;
import org.vidad.data.Tag;

/**
 * @author Moshe Beeri
 *
 */
public class VidoeTagCollector extends Tag{
	Logger log = Logger.getLogger(VidoeTagCollector.class);
	boolean initial = true;
	String status="";
	String taxonomy="";
	
	public String add(){
		initial=false;
		status = taxonomy + " added"; 
		return "added";
	}
	
	public String reset(){
		return "added";
	}

}
