//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.17 at 08:30:24 PM IDT 
//


package org.vidad.data.taxomony;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.vidad.data.Collectionable;
import org.vidad.tools.conf.Collection;
import org.vidad.tools.nosql.Mongodb;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="help" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relations" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="hierarchy" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="multiple" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="nodes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="term" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="vid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vid",
    "name",
    "description",
    "help",
    "relations",
    "hierarchy",
    "multiple",
    "required",
    "tags",
    "module",
    "weight",
    "nodes",
    "term"
})
@XmlRootElement(name = "vocabulary")
public class Vocabulary {

    protected byte vid;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String help;
    protected byte relations;
    protected byte hierarchy;
    protected byte multiple;
    protected byte required;
    protected byte tags;
    @XmlElement(required = true)
    protected String module;
    protected byte weight;
    @XmlElement(required = true)
    protected String nodes;
    protected List<Vocabulary.Term> term;

    
    public static Vocabulary fromFile(Path path) throws JAXBException{
		File file = path.toFile();
		JAXBContext jaxbContext = JAXBContext.newInstance(Vocabulary.class);
		Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
		Vocabulary v = (Vocabulary) jaxbUnmarshaller.unmarshal(file);
    	System.out.println(v.getTerm().size());
    	for(Term t : v.getTerm()){
    		Mongodb.getInstance().insertCollectionable(new Texanomy(t));
    	}
    	return v;
    }
    
    public static void main(String[] args) throws JAXBException {
    	Vocabulary.fromFile(Paths.get("/home/moshe/data/taxonomy/taxonomy_taxonomy.xml.xml"));
	}
    /**
     * Gets the value of the vid property.
     * 
     */
    public byte getVid() {
        return vid;
    }

    /**
     * Sets the value of the vid property.
     * 
     */
    public void setVid(byte value) {
        this.vid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the relations property.
     * 
     */
    public byte getRelations() {
        return relations;
    }

    /**
     * Sets the value of the relations property.
     * 
     */
    public void setRelations(byte value) {
        this.relations = value;
    }

    /**
     * Gets the value of the hierarchy property.
     * 
     */
    public byte getHierarchy() {
        return hierarchy;
    }

    /**
     * Sets the value of the hierarchy property.
     * 
     */
    public void setHierarchy(byte value) {
        this.hierarchy = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     */
    public byte getMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     * 
     */
    public void setMultiple(byte value) {
        this.multiple = value;
    }

    /**
     * Gets the value of the required property.
     * 
     */
    public byte getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     */
    public void setRequired(byte value) {
        this.required = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     */
    public byte getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     */
    public void setTags(byte value) {
        this.tags = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public byte getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(byte value) {
        this.weight = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodes(String value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the term property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vocabulary.Term }
     * 
     * 
     */
    public List<Vocabulary.Term> getTerm() {
        if (term == null) {
            term = new ArrayList<Vocabulary.Term>();
        }
        return this.term;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="vid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    
    public static class Texanomy extends Collectionable<Texanomy>{

        protected int 		tid;
        protected String 	name;
        protected String 	description;
        protected int 		weight;
        protected int 		depth;
        protected int 		parent;
        
		@Override
		public Collection getCollection() {
			return Collection.TAXANOMY;
		}
		
		public Texanomy(int tid, String name, String description, int weight,
				int depth, int parent) {
			super();
			this.tid = tid;
			this.name = name;
			this.description = description;
			this.weight = weight;
			this.depth = depth;
			this.parent = parent;
		}

		public Texanomy(Term t) {
			this(t.tid, t.name, t.description,t.weight,t.depth,t.parent);
		}
    }
    
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tid",
        "vid",
        "name",
        "description",
        "weight",
        "depth",
        "parent"
    })
    public static class Term {

        protected int tid;
        protected byte vid;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String description;
        protected byte weight;
        protected byte depth;
        protected int parent;

        /**
         * Gets the value of the tid property.
         * 
         */
        public int getTid() {
            return tid;
        }

        /**
         * Sets the value of the tid property.
         * 
         */
        public void setTid(int value) {
            this.tid = value;
        }

        /**
         * Gets the value of the vid property.
         * 
         */
        public byte getVid() {
            return vid;
        }

        /**
         * Sets the value of the vid property.
         * 
         */
        public void setVid(byte value) {
            this.vid = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public byte getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(byte value) {
            this.weight = value;
        }

        /**
         * Gets the value of the depth property.
         * 
         */
        public byte getDepth() {
            return depth;
        }

        /**
         * Sets the value of the depth property.
         * 
         */
        public void setDepth(byte value) {
            this.depth = value;
        }

        /**
         * Gets the value of the parent property.
         * 
         */
        public int getParent() {
            return parent;
        }

        /**
         * Sets the value of the parent property.
         * 
         */
        public void setParent(int value) {
            this.parent = value;
        }

    }

}
