/**
 * This file was generated by Moshe Beeri
 * May 1, 2013
 * com.orbograph.data
 */
package org.vidad.data;

import java.lang.reflect.ParameterizedType;

import org.bson.types.ObjectId;
import org.vidad.tools.conf.Collection;

import com.google.gson.Gson;


/**
 * @author Moshe Beeri
 *
 */
public abstract class Collectionable<T> {
	transient Gson gson = new Gson();
	ObjectId objectId;
	
	abstract public Collection getCollection();
	
	public ObjectId getObjectId(){
		return objectId;
	}
	public void setObjectId(ObjectId id){
		objectId = id;
	}

	public String toJson()
	{
		return gson.toJson(this);
	}
	
	public T fromJson(String json)
	{
		@SuppressWarnings("unchecked")
		Class<T> t = (Class<T>) ((ParameterizedType) getClass()
                .getGenericSuperclass()).getActualTypeArguments()[0];
		return gson.fromJson(json, t);
	}
}
