/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.data
 */
package org.vidad.data;

import org.apache.log4j.Logger;
import org.bson.types.ObjectId;

/**
 * @author Moshe Beeri
 *
 */
public class Task {
	transient Logger log = Logger.getLogger(Task.class);
	
	ObjectId exceptionId;
	/**
	 * @return the exceptionId
	 */
	public ObjectId getExceptionId() {
		return exceptionId;
	}
	/**
	 * @param exceptionId the exceptionId to set
	 */
	public void setExceptionId(ObjectId exceptionId) {
		this.exceptionId = exceptionId;
	}

	
}
