/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.data
 */
package org.vidad.data;

import org.apache.log4j.Logger;
import org.vidad.tools.conf.Collection;

/**
 * @author Moshe Beeri
 *
 */
public class Video extends Collectionable<Video>{
	transient Logger log = Logger.getLogger(Video.class);

	/**
	 * @return
	 * @see org.vidad.data.Collectionable#getCollection()
	 */
	@Override
	public Collection getCollection() {
		return Collection.VIDEO;
	}
}
