/**
 * This file was generated by Moshe Beeri
 * Aug 7, 2013
 * org.vidad.data
 */
package org.vidad.data;

import java.io.Serializable;
import java.util.Date;

import org.apache.log4j.Logger;
import org.joda.time.DateTime;
import org.vidad.tools.conf.Collection;
import org.vidad.video.xuggle.VideoInfo;

/**
 * @author Moshe Beeri
 * 
 */
public class Video extends Collectionable<Video> implements Serializable {
	private static final long serialVersionUID = -2798571933254021201L;

	transient Logger log = Logger.getLogger(Video.class);

	String title;
	String extension;
	String videoURL;
	Date receivedTime;
	VideoInfo info;

	public Video() {
		super();
	}

	/**
	 * @param videoURL
	 * @param extension
	 */
	public Video(String videoURL, String extension) {
		super();
		this.extension = extension;
		this.videoURL = videoURL;
		this.receivedTime = new DateTime().toDate();
	}

	public String getExtension() {
		return extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getVideoURL() {
		return videoURL;
	}

	public void setVideoURL(String videoURL) {
		this.videoURL = videoURL;
	}

	public Date getReceivedTime() {
		return receivedTime;
	}

	public void setReceivedTime(Date receivedTime) {
		this.receivedTime = receivedTime;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public VideoInfo getInfo() {
		return info;
	}

	public void setInfo(VideoInfo info) {
		this.info = info;
	}

	/**
	 * @return
	 * @see org.vidad.data.Collectionable#getCollection()
	 */
	@Override
	public Collection getCollection() {
		return Collection.VIDEO;
	}
}
