/**
 * This file was generated by Moshe Beeri
 * May 22, 2013
 * com.orbograph.camel.split
 */
package org.vidad.camel;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;
import org.vidad.data.Task;
import org.vidad.data.Tasks;

import com.google.gson.Gson;

/**
 * @author Moshe Beeri
 *
 */
public class JsonListSplitter {
	Logger log = Logger.getLogger(JsonListSplitter.class);
	Gson gson = new Gson();


	/**
     * @param body tasks an List of Tasks formatted in JSON
     * @return a list containing each split task 
     */
	public List<String> splitTasksInJsonList(String body) {
    	List<String> ret = new ArrayList<String>();
    	Tasks tasks = gson.fromJson(body, Tasks.class);
    	for( Task task : tasks){
    		ret.add(gson.toJson(task));
    	}
    	return ret;
    }
}
